### ISSUE TITLE
Visual bug with ram allocation

### ISSUE THREAD

**Issue by SolarPolarMan** [laurent-clouet/sheepit-client#126]
![image](https://cloud.githubusercontent.com/assets/13716824/25504206/ea647740-2b94-11e7-8283-25b7441834c7.png)

sheepit-5.416.2832

**Comment by laurent-clouet** [comment]
I saw this bug few times, if you resize a bit the window, it's much better ?

i'm guessing the way i initialize the window is not the right way. Not sure where come from.

**Comment by SolarPolarMan** [comment]
If I resized the window horizontally it changed nothing but when I changed the size diagonally it fixed its self so I assume it's the vertical height. I just recorded a [video](https://youtu.be/0dHa6baoIBU) and it's definitely due to the height. The default size does this for me but anything larger than that seems fine.

**Comment by laurent-clouet** [comment]
do you still have this with the client 5.475.x ?
(or the latest master)

**Comment by SolarPolarMan** [comment]
The default size no longer does this but the issue's still there if you make it the old default size.

**Comment by goldengel** [comment]
![fullscreenshot - 636292540200333269](https://cloud.githubusercontent.com/assets/1375893/25582584/58c78a64-2e8e-11e7-9fde-6b6ab047c48a.jpg)
![fullscreenshot - 636292539916566368](https://cloud.githubusercontent.com/assets/1375893/25582583/58c73e56-2e8e-11e7-8a85-fbd40044c023.jpg)


With new version sheepit-client-5.475.2834.jar the issue was solved.

**Comment by SolarPolarMan** [comment]
The underlying issue is still there but the work around works. The default size no longer has this issue. Here's a [video](https://youtu.be/H_JWXPu8sBU) showing the same behavior as before, while using sheepit-5.475.2834.exe

**Comment by laurent-clouet** [comment]
I agree with @SolarPolarMan  but for now, it will do.
I really  don't link the current ui but it's the best we got for now.
